apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: hello-world
  description: >-
    Kubernetes v1.31.4
    | 1 CP + 1 Workers
    | Calico
  annotations:
    backstaige.io/kubernetes-version: v1.31.4
    backstaige.io/cp-replicas: "1"
    backstaige.io/worker-replicas: "1"
    backstaige.io/cni: calico
  tags:
    - docker
    - calico
spec:
  type: kubernetes-cluster
  system: backstaige
  owner: infrastructure
  lifecycle: experimental
