apiVersion: backstaige.io/v1alpha1
kind: DockerCluster
metadata:
  name: dev-try
  namespace: default
spec:
  parameters:
    id: dev-try
    kubernetesVersion: "v1.32.8"
    controlPlane:
      replicas: 1
    workers:
      replicas: 1
    podCIDR: "10.244.0.0/16"
    serviceCIDR: "10.96.0.0/12"
    cni: cilium
  writeConnectionSecretToRef:
    name: dev-try-kubeconfig
