apiVersion: backstaige.io/v1alpha1
kind: DockerCluster
metadata:
  name: dev-cluster
  namespace: default
spec:
  parameters:
    id: dev-cluster
    kubernetesVersion: "v1.31.4"
    controlPlane:
      replicas: 1
    workers:
      replicas: 0
    podCIDR: "10.244.0.0/16"
    serviceCIDR: "10.96.0.0/12"
    cni: cilium
  writeConnectionSecretToRef:
    name: dev-cluster-kubeconfig
